name: Scrape

on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:

env:
  FIREBASE_AUTHKEY: ${{secrets.FIREBASE_AUTHKEY}}
  FIREBASE_AUTHKEY_PATH: ${{secrets.FIREBASE_AUTHKEY_PATH}}
  TWITTER_CONSUMER_KEY: ${{secrets.TWITTER_CONSUMER_KEY}}
  TWITTER_CONSUMER_SECRET: ${{secrets.TWITTER_CONSUMER_SECRET}}
  TWITTER_ACCESS_TOKEN: ${{secrets.TWITTER_ACCESS_TOKEN}}
  TWITTER_ACCESS_TOKEN_SECRET: ${{secrets.TWITTER_ACCESS_TOKEN_SECRET}}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Prepare secrets
        run: |
          echo "${FIREBASE_AUTHKEY}" > ${FIREBASE_AUTHKEY_PATH}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Scrape
        run: |
          poetry run python main.py

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
